### ISSUE TITLE
`briefcase create` fails to build the docker image

### ISSUE THREAD

**Issue by NavidSassan** [beeware/briefcase-linux-appimage-template#12] opened 2022-03-11 12:47 UTC
**Describe the bug**
`briefcase create` fails with the following error:
```
STEP 11/18: RUN python${PY_VERSION} -m pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.9/dist-packages (21.2.4)
Collecting pip
  Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
ERROR: Could not install packages due to an OSError: [Errno 39] Directory not empty: 'webencodings'

Error: error building at STEP "RUN python${PY_VERSION} -m pip install --upgrade pip": error while running runtime: exit status 1

Error building Docker container for helloworld.
```
Tested with python 3.9 and 3.10.

**To Reproduce**
1. Follow the tutorial to build an AppImage (https://docs.beeware.org/en/latest/tutorial/tutorial-3.html)
2. `python3.9 -m venv --system-site-packages beeware-venv`
3. `source beeware-venv/bin/activate`
4. `briefcase new`
5. `briefcase create`

**Expected behavior**
No error, the AppImage should be created (I assume ;))

**Environment:**
 - Operating System: Fedora Linux 35 (Thirty Five)
 - Python version: 3.9, also tested with 3.10
 - Software versions:
   - Briefcase: 0.3.6
   - cookiecutter: 1.7.3

**Additional context**
Complete [log.txt](https://github.com/beeware/briefcase-linux-appimage-template/files/8231899/log.txt)

**Comment by freakboy3742** [comment] 2022-03-28 04:52
I believe the issue is the use of `--system-site-packages`. The system site package directory won't be modifiable as an end user, so when briefcase attempts to update code it will fail.

Closing as this appears to be a case of not following the tutorial correctly.

**Closed by freakboy3742** 2022-03-28 04:52 UTC
Labels: bug
